api/urls.py
from rest_framework.routers import DefaultRouter
from api.views import BookReviewsViewSet

app_name = 'api'

router = DefaultRouter()
router.register('reviews', BookReviewsViewSet, basename='review')


urlpatterns = router.urls

books/urls.py
from django.urls import path

from books.views import BooksView, BookDetailView, AddReviewView, EditReviewView, ConfirmDeleteReviewView, DeleteReviewView

app_name = "books"
urlpatterns = [
    path("", BooksView.as_view(), name="list"),
    path("<int:id>", BookDetailView.as_view(), name="detail" ),
    path("<int:id>/reviews/", AddReviewView.as_view(), name="reviews"),
    path("<int:book_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name="edit-review"),
    path("<int:book_id>/reviews/<int:review_id>/delete/confirm/", ConfirmDeleteReviewView.as_view(), name="confirm-delete-review"),
    path("<int:book_id>/reviews/<int:review_id>/delete/", DeleteReviewView.as_view(),
         name="delete-review"),

]

goodreads/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from .views import landing_page, home_page

urlpatterns = [
    path("", landing_page, name="landing_page"),
    path("home/", home_page, name="home"),
    path("users/", include("users.urls")),
    path("books/", include("books.urls")),
    path("api/", include("api.urls")),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import RegisterView, LoginView, LogoutView, ProfileView, ProfileUpdateView

app_name = "users"
urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/edit/", ProfileUpdateView.as_view(), name="profile-edit"),
]

templates/base.html
{% load static %}
{% url 'home' as home_page_url %}
{% url 'books:list' as books_page_url %}
{% url 'users:profile' as profile_page_url %}
{% url 'users:profile-edit' as profile_edit_page_url %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Goodreads Clone{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body class="mx-5">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-3 ">
          <a class="navbar-brand" href="{% url 'landing_page' %}">Goodreads Clone</a>
<!--              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
<!--                <span class="navbar-toggler-icon"></span>-->
<!--              </button>-->

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link {% if request.path == home_page_url %} active {% endif %}" href="{{ home_page_url }}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                  <a class="nav-link {% if request.path == books_page_url %} active {% endif %}" href="{{ books_page_url }}">Books <span class="sr-only">(current)</span></a>
              </li>
            </ul>
            <div>
            {% if request.user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                 <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle {% if request.path == profile_page_url or request.path == profile_edit_page_url %} active {% endif %}" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      {{ request.user.username }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{{ profile_page_url }}">Profile</a>
                      <a class="dropdown-item" href="#">Help</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                    </div>
                 </li>
            </ul>
            {% else %}
                <a class="btn btn-outline-primary active" href="{% url 'users:login' %}">Login</a>
            {% endif %}
            </div>
          </div>

    </nav>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        {% block content %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}Home Page{% endblock %}

{% block content %}
    <h3>All Reviews</h3>

    {% for review in book_reviews %}
        <div class="container posts-content">
            <div class="row">
                <div class="col-lg-6">
                    <div class="card mb-4">
                      <div class="card-body">
                        <div class="media mb-3">
                          <img src="{{ review.user.profile_picture.url }}" class="d-block ui-w-40 rounded-circle" alt="">
                          <div class="media-body ml-3">
                            <b>{{ review.user.username }}</b> rated this book {{ review.stars_given }} stars
                            <div class="text-muted small">{{ review.created_at | date:"M d, Y" }}</div>
                          </div>
                        </div>

                        <p>
                            {{ review.comment | truncatechars:300}}
                        </p>
                        <img class="cover-pic" src="{{ review.book.cover_picture.url }}">
                      </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/landing.html
{% extends "base.html" %}

{% block content %}
    <h1>Landing Page</h1>

    <p>
        Goodreads is an American social cataloging website and a subsidiary of Amazon that allows individuals to search its database of books, annotations, quotes, and reviews. Users can sign up and register books to generate library catalogs and reading lists. They can also create their own groups of book suggestions, surveys, polls, blogs, and discussions. The website's offices are located in San Francisco.
        Goodreads was founded in December 2006 and launched in January 2007 by Otis Chandler and Elizabeth Khuri Chandler. In December 2007, the site had 650,000 members and 10,000,000 books had been added. By July 2012, the site reported 10 million members, 20 million monthly visits, and thirty employees. On March 28, 2013, Amazon announced its acquisition of Goodreads, and by July 23, 2013, Goodreads announced their user base had grown to 20 million members.
    </p>
{% endblock %}